
package com.google.api.ads.adwords.jaxws.v201607.cm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DraftService", targetNamespace = "https://adwords.google.com/api/adwords/cm/v201607", wsdlLocation = "https://adwords.google.com/api/adwords/cm/v201607/DraftService?wsdl")
public class DraftService
    extends Service
{

    private final static URL DRAFTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRAFTSERVICE_EXCEPTION;
    private final static QName DRAFTSERVICE_QNAME = new QName("https://adwords.google.com/api/adwords/cm/v201607", "DraftService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://adwords.google.com/api/adwords/cm/v201607/DraftService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRAFTSERVICE_WSDL_LOCATION = url;
        DRAFTSERVICE_EXCEPTION = e;
    }

    public DraftService() {
        super(__getWsdlLocation(), DRAFTSERVICE_QNAME);
    }

    public DraftService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DraftServiceInterface
     */
    @WebEndpoint(name = "DraftServiceInterfacePort")
    public DraftServiceInterface getDraftServiceInterfacePort() {
        return super.getPort(new QName("https://adwords.google.com/api/adwords/cm/v201607", "DraftServiceInterfacePort"), DraftServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DraftServiceInterface
     */
    @WebEndpoint(name = "DraftServiceInterfacePort")
    public DraftServiceInterface getDraftServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://adwords.google.com/api/adwords/cm/v201607", "DraftServiceInterfacePort"), DraftServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRAFTSERVICE_EXCEPTION!= null) {
            throw DRAFTSERVICE_EXCEPTION;
        }
        return DRAFTSERVICE_WSDL_LOCATION;
    }

}
