//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.12 at 12:06:58 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://adwords.google.com/api/adwords/cm/v201502", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.google.api.ads.adwords.lib.jaxb.v201502;
