/**
 * CurrencyCode.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Mar 02, 2009 (07:08:06 PST) WSDL2Java emitter.
 */

package com.google.api.ads.adwords.axis.v201605.express;

public class CurrencyCode implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected CurrencyCode(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _ADP = "ADP";
    public static final java.lang.String _AED = "AED";
    public static final java.lang.String _AFA = "AFA";
    public static final java.lang.String _AFN = "AFN";
    public static final java.lang.String _ALK = "ALK";
    public static final java.lang.String _ALL = "ALL";
    public static final java.lang.String _AMD = "AMD";
    public static final java.lang.String _ANG = "ANG";
    public static final java.lang.String _AOA = "AOA";
    public static final java.lang.String _AOK = "AOK";
    public static final java.lang.String _AON = "AON";
    public static final java.lang.String _AOR = "AOR";
    public static final java.lang.String _ARA = "ARA";
    public static final java.lang.String _ARL = "ARL";
    public static final java.lang.String _ARM = "ARM";
    public static final java.lang.String _ARP = "ARP";
    public static final java.lang.String _ARS = "ARS";
    public static final java.lang.String _ATS = "ATS";
    public static final java.lang.String _AUD = "AUD";
    public static final java.lang.String _AWG = "AWG";
    public static final java.lang.String _AZM = "AZM";
    public static final java.lang.String _AZN = "AZN";
    public static final java.lang.String _BAD = "BAD";
    public static final java.lang.String _BAM = "BAM";
    public static final java.lang.String _BAN = "BAN";
    public static final java.lang.String _BBD = "BBD";
    public static final java.lang.String _BDT = "BDT";
    public static final java.lang.String _BEF = "BEF";
    public static final java.lang.String _BGL = "BGL";
    public static final java.lang.String _BGM = "BGM";
    public static final java.lang.String _BGN = "BGN";
    public static final java.lang.String _BGO = "BGO";
    public static final java.lang.String _BHD = "BHD";
    public static final java.lang.String _BIF = "BIF";
    public static final java.lang.String _BMD = "BMD";
    public static final java.lang.String _BND = "BND";
    public static final java.lang.String _BOB = "BOB";
    public static final java.lang.String _BOL = "BOL";
    public static final java.lang.String _BOP = "BOP";
    public static final java.lang.String _BRB = "BRB";
    public static final java.lang.String _BRC = "BRC";
    public static final java.lang.String _BRE = "BRE";
    public static final java.lang.String _BRL = "BRL";
    public static final java.lang.String _BRN = "BRN";
    public static final java.lang.String _BRR = "BRR";
    public static final java.lang.String _BRZ = "BRZ";
    public static final java.lang.String _BSD = "BSD";
    public static final java.lang.String _BTN = "BTN";
    public static final java.lang.String _BUK = "BUK";
    public static final java.lang.String _BWP = "BWP";
    public static final java.lang.String _BYB = "BYB";
    public static final java.lang.String _BYR = "BYR";
    public static final java.lang.String _BZD = "BZD";
    public static final java.lang.String _CAD = "CAD";
    public static final java.lang.String _CDF = "CDF";
    public static final java.lang.String _CHF = "CHF";
    public static final java.lang.String _CLE = "CLE";
    public static final java.lang.String _CLF = "CLF";
    public static final java.lang.String _CLP = "CLP";
    public static final java.lang.String _CNY = "CNY";
    public static final java.lang.String _COP = "COP";
    public static final java.lang.String _CRC = "CRC";
    public static final java.lang.String _CSD = "CSD";
    public static final java.lang.String _CSK = "CSK";
    public static final java.lang.String _CUC = "CUC";
    public static final java.lang.String _CUP = "CUP";
    public static final java.lang.String _CVE = "CVE";
    public static final java.lang.String _CYP = "CYP";
    public static final java.lang.String _CZK = "CZK";
    public static final java.lang.String _DDM = "DDM";
    public static final java.lang.String _DEM = "DEM";
    public static final java.lang.String _DJF = "DJF";
    public static final java.lang.String _DKK = "DKK";
    public static final java.lang.String _DOP = "DOP";
    public static final java.lang.String _DZD = "DZD";
    public static final java.lang.String _ECS = "ECS";
    public static final java.lang.String _EEK = "EEK";
    public static final java.lang.String _EGP = "EGP";
    public static final java.lang.String _ERN = "ERN";
    public static final java.lang.String _ESP = "ESP";
    public static final java.lang.String _ETB = "ETB";
    public static final java.lang.String _EUR = "EUR";
    public static final java.lang.String _FIM = "FIM";
    public static final java.lang.String _FJD = "FJD";
    public static final java.lang.String _FKP = "FKP";
    public static final java.lang.String _FRF = "FRF";
    public static final java.lang.String _GBP = "GBP";
    public static final java.lang.String _GEK = "GEK";
    public static final java.lang.String _GEL = "GEL";
    public static final java.lang.String _GHC = "GHC";
    public static final java.lang.String _GHP = "GHP";
    public static final java.lang.String _GHS = "GHS";
    public static final java.lang.String _GIP = "GIP";
    public static final java.lang.String _GMD = "GMD";
    public static final java.lang.String _GNF = "GNF";
    public static final java.lang.String _GNS = "GNS";
    public static final java.lang.String _GQE = "GQE";
    public static final java.lang.String _GRD = "GRD";
    public static final java.lang.String _GTQ = "GTQ";
    public static final java.lang.String _GWE = "GWE";
    public static final java.lang.String _GWP = "GWP";
    public static final java.lang.String _GYD = "GYD";
    public static final java.lang.String _HKD = "HKD";
    public static final java.lang.String _HNL = "HNL";
    public static final java.lang.String _HRD = "HRD";
    public static final java.lang.String _HRK = "HRK";
    public static final java.lang.String _HTG = "HTG";
    public static final java.lang.String _HUF = "HUF";
    public static final java.lang.String _IDR = "IDR";
    public static final java.lang.String _IEP = "IEP";
    public static final java.lang.String _ILP = "ILP";
    public static final java.lang.String _ILR = "ILR";
    public static final java.lang.String _ILS = "ILS";
    public static final java.lang.String _INR = "INR";
    public static final java.lang.String _IQD = "IQD";
    public static final java.lang.String _IRR = "IRR";
    public static final java.lang.String _ISJ = "ISJ";
    public static final java.lang.String _ISK = "ISK";
    public static final java.lang.String _ITL = "ITL";
    public static final java.lang.String _JMD = "JMD";
    public static final java.lang.String _JOD = "JOD";
    public static final java.lang.String _JPY = "JPY";
    public static final java.lang.String _KES = "KES";
    public static final java.lang.String _KGS = "KGS";
    public static final java.lang.String _KHR = "KHR";
    public static final java.lang.String _KMF = "KMF";
    public static final java.lang.String _KPW = "KPW";
    public static final java.lang.String _KRH = "KRH";
    public static final java.lang.String _KRO = "KRO";
    public static final java.lang.String _KRW = "KRW";
    public static final java.lang.String _KWD = "KWD";
    public static final java.lang.String _KYD = "KYD";
    public static final java.lang.String _KZT = "KZT";
    public static final java.lang.String _LAK = "LAK";
    public static final java.lang.String _LBP = "LBP";
    public static final java.lang.String _LKR = "LKR";
    public static final java.lang.String _LRD = "LRD";
    public static final java.lang.String _LSL = "LSL";
    public static final java.lang.String _LTL = "LTL";
    public static final java.lang.String _LTT = "LTT";
    public static final java.lang.String _LUF = "LUF";
    public static final java.lang.String _LVL = "LVL";
    public static final java.lang.String _LVR = "LVR";
    public static final java.lang.String _LYD = "LYD";
    public static final java.lang.String _MAD = "MAD";
    public static final java.lang.String _MAF = "MAF";
    public static final java.lang.String _MCF = "MCF";
    public static final java.lang.String _MDC = "MDC";
    public static final java.lang.String _MDL = "MDL";
    public static final java.lang.String _MGA = "MGA";
    public static final java.lang.String _MGF = "MGF";
    public static final java.lang.String _MKD = "MKD";
    public static final java.lang.String _MKN = "MKN";
    public static final java.lang.String _MLF = "MLF";
    public static final java.lang.String _MMK = "MMK";
    public static final java.lang.String _MNT = "MNT";
    public static final java.lang.String _MOP = "MOP";
    public static final java.lang.String _MRO = "MRO";
    public static final java.lang.String _MTL = "MTL";
    public static final java.lang.String _MTP = "MTP";
    public static final java.lang.String _MUR = "MUR";
    public static final java.lang.String _MVR = "MVR";
    public static final java.lang.String _MWK = "MWK";
    public static final java.lang.String _MXN = "MXN";
    public static final java.lang.String _MXP = "MXP";
    public static final java.lang.String _MYR = "MYR";
    public static final java.lang.String _MZE = "MZE";
    public static final java.lang.String _MZM = "MZM";
    public static final java.lang.String _MZN = "MZN";
    public static final java.lang.String _NAD = "NAD";
    public static final java.lang.String _NGN = "NGN";
    public static final java.lang.String _NIC = "NIC";
    public static final java.lang.String _NIO = "NIO";
    public static final java.lang.String _NLG = "NLG";
    public static final java.lang.String _NOK = "NOK";
    public static final java.lang.String _NPR = "NPR";
    public static final java.lang.String _NZD = "NZD";
    public static final java.lang.String _OMR = "OMR";
    public static final java.lang.String _PAB = "PAB";
    public static final java.lang.String _PEI = "PEI";
    public static final java.lang.String _PEN = "PEN";
    public static final java.lang.String _PES = "PES";
    public static final java.lang.String _PGK = "PGK";
    public static final java.lang.String _PHP = "PHP";
    public static final java.lang.String _PKR = "PKR";
    public static final java.lang.String _PLN = "PLN";
    public static final java.lang.String _PLZ = "PLZ";
    public static final java.lang.String _PTE = "PTE";
    public static final java.lang.String _PYG = "PYG";
    public static final java.lang.String _QAR = "QAR";
    public static final java.lang.String _RHD = "RHD";
    public static final java.lang.String _ROL = "ROL";
    public static final java.lang.String _RON = "RON";
    public static final java.lang.String _RSD = "RSD";
    public static final java.lang.String _RUB = "RUB";
    public static final java.lang.String _RUR = "RUR";
    public static final java.lang.String _RWF = "RWF";
    public static final java.lang.String _SAR = "SAR";
    public static final java.lang.String _SBD = "SBD";
    public static final java.lang.String _SCR = "SCR";
    public static final java.lang.String _SDD = "SDD";
    public static final java.lang.String _SDG = "SDG";
    public static final java.lang.String _SDP = "SDP";
    public static final java.lang.String _SEK = "SEK";
    public static final java.lang.String _SGD = "SGD";
    public static final java.lang.String _SHP = "SHP";
    public static final java.lang.String _SIT = "SIT";
    public static final java.lang.String _SKK = "SKK";
    public static final java.lang.String _SLL = "SLL";
    public static final java.lang.String _SOS = "SOS";
    public static final java.lang.String _SRD = "SRD";
    public static final java.lang.String _SRG = "SRG";
    public static final java.lang.String _SSP = "SSP";
    public static final java.lang.String _STD = "STD";
    public static final java.lang.String _SUR = "SUR";
    public static final java.lang.String _SVC = "SVC";
    public static final java.lang.String _SYP = "SYP";
    public static final java.lang.String _SZL = "SZL";
    public static final java.lang.String _THB = "THB";
    public static final java.lang.String _TJR = "TJR";
    public static final java.lang.String _TJS = "TJS";
    public static final java.lang.String _TMM = "TMM";
    public static final java.lang.String _TMT = "TMT";
    public static final java.lang.String _TND = "TND";
    public static final java.lang.String _TOP = "TOP";
    public static final java.lang.String _TPE = "TPE";
    public static final java.lang.String _TRL = "TRL";
    public static final java.lang.String _TRY = "TRY";
    public static final java.lang.String _TTD = "TTD";
    public static final java.lang.String _TWD = "TWD";
    public static final java.lang.String _TZS = "TZS";
    public static final java.lang.String _UAH = "UAH";
    public static final java.lang.String _UAK = "UAK";
    public static final java.lang.String _UGS = "UGS";
    public static final java.lang.String _UGX = "UGX";
    public static final java.lang.String _USD = "USD";
    public static final java.lang.String _UYP = "UYP";
    public static final java.lang.String _UYU = "UYU";
    public static final java.lang.String _UZS = "UZS";
    public static final java.lang.String _VEB = "VEB";
    public static final java.lang.String _VEF = "VEF";
    public static final java.lang.String _VND = "VND";
    public static final java.lang.String _VNN = "VNN";
    public static final java.lang.String _VUV = "VUV";
    public static final java.lang.String _WST = "WST";
    public static final java.lang.String _XAF = "XAF";
    public static final java.lang.String _XCD = "XCD";
    public static final java.lang.String _XOF = "XOF";
    public static final java.lang.String _XPF = "XPF";
    public static final java.lang.String _XXX = "XXX";
    public static final java.lang.String _YDD = "YDD";
    public static final java.lang.String _YER = "YER";
    public static final java.lang.String _YUD = "YUD";
    public static final java.lang.String _YUM = "YUM";
    public static final java.lang.String _YUN = "YUN";
    public static final java.lang.String _YUR = "YUR";
    public static final java.lang.String _ZAR = "ZAR";
    public static final java.lang.String _ZMK = "ZMK";
    public static final java.lang.String _ZMW = "ZMW";
    public static final java.lang.String _ZRN = "ZRN";
    public static final java.lang.String _ZRZ = "ZRZ";
    public static final java.lang.String _ZWD = "ZWD";
    public static final java.lang.String _ZWL = "ZWL";
    public static final java.lang.String _ZWR = "ZWR";
    public static final CurrencyCode ADP = new CurrencyCode(_ADP);
    public static final CurrencyCode AED = new CurrencyCode(_AED);
    public static final CurrencyCode AFA = new CurrencyCode(_AFA);
    public static final CurrencyCode AFN = new CurrencyCode(_AFN);
    public static final CurrencyCode ALK = new CurrencyCode(_ALK);
    public static final CurrencyCode ALL = new CurrencyCode(_ALL);
    public static final CurrencyCode AMD = new CurrencyCode(_AMD);
    public static final CurrencyCode ANG = new CurrencyCode(_ANG);
    public static final CurrencyCode AOA = new CurrencyCode(_AOA);
    public static final CurrencyCode AOK = new CurrencyCode(_AOK);
    public static final CurrencyCode AON = new CurrencyCode(_AON);
    public static final CurrencyCode AOR = new CurrencyCode(_AOR);
    public static final CurrencyCode ARA = new CurrencyCode(_ARA);
    public static final CurrencyCode ARL = new CurrencyCode(_ARL);
    public static final CurrencyCode ARM = new CurrencyCode(_ARM);
    public static final CurrencyCode ARP = new CurrencyCode(_ARP);
    public static final CurrencyCode ARS = new CurrencyCode(_ARS);
    public static final CurrencyCode ATS = new CurrencyCode(_ATS);
    public static final CurrencyCode AUD = new CurrencyCode(_AUD);
    public static final CurrencyCode AWG = new CurrencyCode(_AWG);
    public static final CurrencyCode AZM = new CurrencyCode(_AZM);
    public static final CurrencyCode AZN = new CurrencyCode(_AZN);
    public static final CurrencyCode BAD = new CurrencyCode(_BAD);
    public static final CurrencyCode BAM = new CurrencyCode(_BAM);
    public static final CurrencyCode BAN = new CurrencyCode(_BAN);
    public static final CurrencyCode BBD = new CurrencyCode(_BBD);
    public static final CurrencyCode BDT = new CurrencyCode(_BDT);
    public static final CurrencyCode BEF = new CurrencyCode(_BEF);
    public static final CurrencyCode BGL = new CurrencyCode(_BGL);
    public static final CurrencyCode BGM = new CurrencyCode(_BGM);
    public static final CurrencyCode BGN = new CurrencyCode(_BGN);
    public static final CurrencyCode BGO = new CurrencyCode(_BGO);
    public static final CurrencyCode BHD = new CurrencyCode(_BHD);
    public static final CurrencyCode BIF = new CurrencyCode(_BIF);
    public static final CurrencyCode BMD = new CurrencyCode(_BMD);
    public static final CurrencyCode BND = new CurrencyCode(_BND);
    public static final CurrencyCode BOB = new CurrencyCode(_BOB);
    public static final CurrencyCode BOL = new CurrencyCode(_BOL);
    public static final CurrencyCode BOP = new CurrencyCode(_BOP);
    public static final CurrencyCode BRB = new CurrencyCode(_BRB);
    public static final CurrencyCode BRC = new CurrencyCode(_BRC);
    public static final CurrencyCode BRE = new CurrencyCode(_BRE);
    public static final CurrencyCode BRL = new CurrencyCode(_BRL);
    public static final CurrencyCode BRN = new CurrencyCode(_BRN);
    public static final CurrencyCode BRR = new CurrencyCode(_BRR);
    public static final CurrencyCode BRZ = new CurrencyCode(_BRZ);
    public static final CurrencyCode BSD = new CurrencyCode(_BSD);
    public static final CurrencyCode BTN = new CurrencyCode(_BTN);
    public static final CurrencyCode BUK = new CurrencyCode(_BUK);
    public static final CurrencyCode BWP = new CurrencyCode(_BWP);
    public static final CurrencyCode BYB = new CurrencyCode(_BYB);
    public static final CurrencyCode BYR = new CurrencyCode(_BYR);
    public static final CurrencyCode BZD = new CurrencyCode(_BZD);
    public static final CurrencyCode CAD = new CurrencyCode(_CAD);
    public static final CurrencyCode CDF = new CurrencyCode(_CDF);
    public static final CurrencyCode CHF = new CurrencyCode(_CHF);
    public static final CurrencyCode CLE = new CurrencyCode(_CLE);
    public static final CurrencyCode CLF = new CurrencyCode(_CLF);
    public static final CurrencyCode CLP = new CurrencyCode(_CLP);
    public static final CurrencyCode CNY = new CurrencyCode(_CNY);
    public static final CurrencyCode COP = new CurrencyCode(_COP);
    public static final CurrencyCode CRC = new CurrencyCode(_CRC);
    public static final CurrencyCode CSD = new CurrencyCode(_CSD);
    public static final CurrencyCode CSK = new CurrencyCode(_CSK);
    public static final CurrencyCode CUC = new CurrencyCode(_CUC);
    public static final CurrencyCode CUP = new CurrencyCode(_CUP);
    public static final CurrencyCode CVE = new CurrencyCode(_CVE);
    public static final CurrencyCode CYP = new CurrencyCode(_CYP);
    public static final CurrencyCode CZK = new CurrencyCode(_CZK);
    public static final CurrencyCode DDM = new CurrencyCode(_DDM);
    public static final CurrencyCode DEM = new CurrencyCode(_DEM);
    public static final CurrencyCode DJF = new CurrencyCode(_DJF);
    public static final CurrencyCode DKK = new CurrencyCode(_DKK);
    public static final CurrencyCode DOP = new CurrencyCode(_DOP);
    public static final CurrencyCode DZD = new CurrencyCode(_DZD);
    public static final CurrencyCode ECS = new CurrencyCode(_ECS);
    public static final CurrencyCode EEK = new CurrencyCode(_EEK);
    public static final CurrencyCode EGP = new CurrencyCode(_EGP);
    public static final CurrencyCode ERN = new CurrencyCode(_ERN);
    public static final CurrencyCode ESP = new CurrencyCode(_ESP);
    public static final CurrencyCode ETB = new CurrencyCode(_ETB);
    public static final CurrencyCode EUR = new CurrencyCode(_EUR);
    public static final CurrencyCode FIM = new CurrencyCode(_FIM);
    public static final CurrencyCode FJD = new CurrencyCode(_FJD);
    public static final CurrencyCode FKP = new CurrencyCode(_FKP);
    public static final CurrencyCode FRF = new CurrencyCode(_FRF);
    public static final CurrencyCode GBP = new CurrencyCode(_GBP);
    public static final CurrencyCode GEK = new CurrencyCode(_GEK);
    public static final CurrencyCode GEL = new CurrencyCode(_GEL);
    public static final CurrencyCode GHC = new CurrencyCode(_GHC);
    public static final CurrencyCode GHP = new CurrencyCode(_GHP);
    public static final CurrencyCode GHS = new CurrencyCode(_GHS);
    public static final CurrencyCode GIP = new CurrencyCode(_GIP);
    public static final CurrencyCode GMD = new CurrencyCode(_GMD);
    public static final CurrencyCode GNF = new CurrencyCode(_GNF);
    public static final CurrencyCode GNS = new CurrencyCode(_GNS);
    public static final CurrencyCode GQE = new CurrencyCode(_GQE);
    public static final CurrencyCode GRD = new CurrencyCode(_GRD);
    public static final CurrencyCode GTQ = new CurrencyCode(_GTQ);
    public static final CurrencyCode GWE = new CurrencyCode(_GWE);
    public static final CurrencyCode GWP = new CurrencyCode(_GWP);
    public static final CurrencyCode GYD = new CurrencyCode(_GYD);
    public static final CurrencyCode HKD = new CurrencyCode(_HKD);
    public static final CurrencyCode HNL = new CurrencyCode(_HNL);
    public static final CurrencyCode HRD = new CurrencyCode(_HRD);
    public static final CurrencyCode HRK = new CurrencyCode(_HRK);
    public static final CurrencyCode HTG = new CurrencyCode(_HTG);
    public static final CurrencyCode HUF = new CurrencyCode(_HUF);
    public static final CurrencyCode IDR = new CurrencyCode(_IDR);
    public static final CurrencyCode IEP = new CurrencyCode(_IEP);
    public static final CurrencyCode ILP = new CurrencyCode(_ILP);
    public static final CurrencyCode ILR = new CurrencyCode(_ILR);
    public static final CurrencyCode ILS = new CurrencyCode(_ILS);
    public static final CurrencyCode INR = new CurrencyCode(_INR);
    public static final CurrencyCode IQD = new CurrencyCode(_IQD);
    public static final CurrencyCode IRR = new CurrencyCode(_IRR);
    public static final CurrencyCode ISJ = new CurrencyCode(_ISJ);
    public static final CurrencyCode ISK = new CurrencyCode(_ISK);
    public static final CurrencyCode ITL = new CurrencyCode(_ITL);
    public static final CurrencyCode JMD = new CurrencyCode(_JMD);
    public static final CurrencyCode JOD = new CurrencyCode(_JOD);
    public static final CurrencyCode JPY = new CurrencyCode(_JPY);
    public static final CurrencyCode KES = new CurrencyCode(_KES);
    public static final CurrencyCode KGS = new CurrencyCode(_KGS);
    public static final CurrencyCode KHR = new CurrencyCode(_KHR);
    public static final CurrencyCode KMF = new CurrencyCode(_KMF);
    public static final CurrencyCode KPW = new CurrencyCode(_KPW);
    public static final CurrencyCode KRH = new CurrencyCode(_KRH);
    public static final CurrencyCode KRO = new CurrencyCode(_KRO);
    public static final CurrencyCode KRW = new CurrencyCode(_KRW);
    public static final CurrencyCode KWD = new CurrencyCode(_KWD);
    public static final CurrencyCode KYD = new CurrencyCode(_KYD);
    public static final CurrencyCode KZT = new CurrencyCode(_KZT);
    public static final CurrencyCode LAK = new CurrencyCode(_LAK);
    public static final CurrencyCode LBP = new CurrencyCode(_LBP);
    public static final CurrencyCode LKR = new CurrencyCode(_LKR);
    public static final CurrencyCode LRD = new CurrencyCode(_LRD);
    public static final CurrencyCode LSL = new CurrencyCode(_LSL);
    public static final CurrencyCode LTL = new CurrencyCode(_LTL);
    public static final CurrencyCode LTT = new CurrencyCode(_LTT);
    public static final CurrencyCode LUF = new CurrencyCode(_LUF);
    public static final CurrencyCode LVL = new CurrencyCode(_LVL);
    public static final CurrencyCode LVR = new CurrencyCode(_LVR);
    public static final CurrencyCode LYD = new CurrencyCode(_LYD);
    public static final CurrencyCode MAD = new CurrencyCode(_MAD);
    public static final CurrencyCode MAF = new CurrencyCode(_MAF);
    public static final CurrencyCode MCF = new CurrencyCode(_MCF);
    public static final CurrencyCode MDC = new CurrencyCode(_MDC);
    public static final CurrencyCode MDL = new CurrencyCode(_MDL);
    public static final CurrencyCode MGA = new CurrencyCode(_MGA);
    public static final CurrencyCode MGF = new CurrencyCode(_MGF);
    public static final CurrencyCode MKD = new CurrencyCode(_MKD);
    public static final CurrencyCode MKN = new CurrencyCode(_MKN);
    public static final CurrencyCode MLF = new CurrencyCode(_MLF);
    public static final CurrencyCode MMK = new CurrencyCode(_MMK);
    public static final CurrencyCode MNT = new CurrencyCode(_MNT);
    public static final CurrencyCode MOP = new CurrencyCode(_MOP);
    public static final CurrencyCode MRO = new CurrencyCode(_MRO);
    public static final CurrencyCode MTL = new CurrencyCode(_MTL);
    public static final CurrencyCode MTP = new CurrencyCode(_MTP);
    public static final CurrencyCode MUR = new CurrencyCode(_MUR);
    public static final CurrencyCode MVR = new CurrencyCode(_MVR);
    public static final CurrencyCode MWK = new CurrencyCode(_MWK);
    public static final CurrencyCode MXN = new CurrencyCode(_MXN);
    public static final CurrencyCode MXP = new CurrencyCode(_MXP);
    public static final CurrencyCode MYR = new CurrencyCode(_MYR);
    public static final CurrencyCode MZE = new CurrencyCode(_MZE);
    public static final CurrencyCode MZM = new CurrencyCode(_MZM);
    public static final CurrencyCode MZN = new CurrencyCode(_MZN);
    public static final CurrencyCode NAD = new CurrencyCode(_NAD);
    public static final CurrencyCode NGN = new CurrencyCode(_NGN);
    public static final CurrencyCode NIC = new CurrencyCode(_NIC);
    public static final CurrencyCode NIO = new CurrencyCode(_NIO);
    public static final CurrencyCode NLG = new CurrencyCode(_NLG);
    public static final CurrencyCode NOK = new CurrencyCode(_NOK);
    public static final CurrencyCode NPR = new CurrencyCode(_NPR);
    public static final CurrencyCode NZD = new CurrencyCode(_NZD);
    public static final CurrencyCode OMR = new CurrencyCode(_OMR);
    public static final CurrencyCode PAB = new CurrencyCode(_PAB);
    public static final CurrencyCode PEI = new CurrencyCode(_PEI);
    public static final CurrencyCode PEN = new CurrencyCode(_PEN);
    public static final CurrencyCode PES = new CurrencyCode(_PES);
    public static final CurrencyCode PGK = new CurrencyCode(_PGK);
    public static final CurrencyCode PHP = new CurrencyCode(_PHP);
    public static final CurrencyCode PKR = new CurrencyCode(_PKR);
    public static final CurrencyCode PLN = new CurrencyCode(_PLN);
    public static final CurrencyCode PLZ = new CurrencyCode(_PLZ);
    public static final CurrencyCode PTE = new CurrencyCode(_PTE);
    public static final CurrencyCode PYG = new CurrencyCode(_PYG);
    public static final CurrencyCode QAR = new CurrencyCode(_QAR);
    public static final CurrencyCode RHD = new CurrencyCode(_RHD);
    public static final CurrencyCode ROL = new CurrencyCode(_ROL);
    public static final CurrencyCode RON = new CurrencyCode(_RON);
    public static final CurrencyCode RSD = new CurrencyCode(_RSD);
    public static final CurrencyCode RUB = new CurrencyCode(_RUB);
    public static final CurrencyCode RUR = new CurrencyCode(_RUR);
    public static final CurrencyCode RWF = new CurrencyCode(_RWF);
    public static final CurrencyCode SAR = new CurrencyCode(_SAR);
    public static final CurrencyCode SBD = new CurrencyCode(_SBD);
    public static final CurrencyCode SCR = new CurrencyCode(_SCR);
    public static final CurrencyCode SDD = new CurrencyCode(_SDD);
    public static final CurrencyCode SDG = new CurrencyCode(_SDG);
    public static final CurrencyCode SDP = new CurrencyCode(_SDP);
    public static final CurrencyCode SEK = new CurrencyCode(_SEK);
    public static final CurrencyCode SGD = new CurrencyCode(_SGD);
    public static final CurrencyCode SHP = new CurrencyCode(_SHP);
    public static final CurrencyCode SIT = new CurrencyCode(_SIT);
    public static final CurrencyCode SKK = new CurrencyCode(_SKK);
    public static final CurrencyCode SLL = new CurrencyCode(_SLL);
    public static final CurrencyCode SOS = new CurrencyCode(_SOS);
    public static final CurrencyCode SRD = new CurrencyCode(_SRD);
    public static final CurrencyCode SRG = new CurrencyCode(_SRG);
    public static final CurrencyCode SSP = new CurrencyCode(_SSP);
    public static final CurrencyCode STD = new CurrencyCode(_STD);
    public static final CurrencyCode SUR = new CurrencyCode(_SUR);
    public static final CurrencyCode SVC = new CurrencyCode(_SVC);
    public static final CurrencyCode SYP = new CurrencyCode(_SYP);
    public static final CurrencyCode SZL = new CurrencyCode(_SZL);
    public static final CurrencyCode THB = new CurrencyCode(_THB);
    public static final CurrencyCode TJR = new CurrencyCode(_TJR);
    public static final CurrencyCode TJS = new CurrencyCode(_TJS);
    public static final CurrencyCode TMM = new CurrencyCode(_TMM);
    public static final CurrencyCode TMT = new CurrencyCode(_TMT);
    public static final CurrencyCode TND = new CurrencyCode(_TND);
    public static final CurrencyCode TOP = new CurrencyCode(_TOP);
    public static final CurrencyCode TPE = new CurrencyCode(_TPE);
    public static final CurrencyCode TRL = new CurrencyCode(_TRL);
    public static final CurrencyCode TRY = new CurrencyCode(_TRY);
    public static final CurrencyCode TTD = new CurrencyCode(_TTD);
    public static final CurrencyCode TWD = new CurrencyCode(_TWD);
    public static final CurrencyCode TZS = new CurrencyCode(_TZS);
    public static final CurrencyCode UAH = new CurrencyCode(_UAH);
    public static final CurrencyCode UAK = new CurrencyCode(_UAK);
    public static final CurrencyCode UGS = new CurrencyCode(_UGS);
    public static final CurrencyCode UGX = new CurrencyCode(_UGX);
    public static final CurrencyCode USD = new CurrencyCode(_USD);
    public static final CurrencyCode UYP = new CurrencyCode(_UYP);
    public static final CurrencyCode UYU = new CurrencyCode(_UYU);
    public static final CurrencyCode UZS = new CurrencyCode(_UZS);
    public static final CurrencyCode VEB = new CurrencyCode(_VEB);
    public static final CurrencyCode VEF = new CurrencyCode(_VEF);
    public static final CurrencyCode VND = new CurrencyCode(_VND);
    public static final CurrencyCode VNN = new CurrencyCode(_VNN);
    public static final CurrencyCode VUV = new CurrencyCode(_VUV);
    public static final CurrencyCode WST = new CurrencyCode(_WST);
    public static final CurrencyCode XAF = new CurrencyCode(_XAF);
    public static final CurrencyCode XCD = new CurrencyCode(_XCD);
    public static final CurrencyCode XOF = new CurrencyCode(_XOF);
    public static final CurrencyCode XPF = new CurrencyCode(_XPF);
    public static final CurrencyCode XXX = new CurrencyCode(_XXX);
    public static final CurrencyCode YDD = new CurrencyCode(_YDD);
    public static final CurrencyCode YER = new CurrencyCode(_YER);
    public static final CurrencyCode YUD = new CurrencyCode(_YUD);
    public static final CurrencyCode YUM = new CurrencyCode(_YUM);
    public static final CurrencyCode YUN = new CurrencyCode(_YUN);
    public static final CurrencyCode YUR = new CurrencyCode(_YUR);
    public static final CurrencyCode ZAR = new CurrencyCode(_ZAR);
    public static final CurrencyCode ZMK = new CurrencyCode(_ZMK);
    public static final CurrencyCode ZMW = new CurrencyCode(_ZMW);
    public static final CurrencyCode ZRN = new CurrencyCode(_ZRN);
    public static final CurrencyCode ZRZ = new CurrencyCode(_ZRZ);
    public static final CurrencyCode ZWD = new CurrencyCode(_ZWD);
    public static final CurrencyCode ZWL = new CurrencyCode(_ZWL);
    public static final CurrencyCode ZWR = new CurrencyCode(_ZWR);
    public java.lang.String getValue() { return _value_;}
    public static CurrencyCode fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        CurrencyCode enumeration = (CurrencyCode)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static CurrencyCode fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(CurrencyCode.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("https://adwords.google.com/api/adwords/express/v201605", "CurrencyCode"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
