
package com.google.api.ads.dfp.jaxws.v201408;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CustomTargetingService", targetNamespace = "https://www.google.com/apis/ads/publisher/v201408", wsdlLocation = "https://ads.google.com/apis/ads/publisher/v201408/CustomTargetingService?wsdl")
public class CustomTargetingService
    extends Service
{

    private final static URL CUSTOMTARGETINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMTARGETINGSERVICE_EXCEPTION;
    private final static QName CUSTOMTARGETINGSERVICE_QNAME = new QName("https://www.google.com/apis/ads/publisher/v201408", "CustomTargetingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ads.google.com/apis/ads/publisher/v201408/CustomTargetingService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMTARGETINGSERVICE_WSDL_LOCATION = url;
        CUSTOMTARGETINGSERVICE_EXCEPTION = e;
    }

    public CustomTargetingService() {
        super(__getWsdlLocation(), CUSTOMTARGETINGSERVICE_QNAME);
    }

    public CustomTargetingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CustomTargetingServiceInterface
     */
    @WebEndpoint(name = "CustomTargetingServiceInterfacePort")
    public CustomTargetingServiceInterface getCustomTargetingServiceInterfacePort() {
        return super.getPort(new QName("https://www.google.com/apis/ads/publisher/v201408", "CustomTargetingServiceInterfacePort"), CustomTargetingServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomTargetingServiceInterface
     */
    @WebEndpoint(name = "CustomTargetingServiceInterfacePort")
    public CustomTargetingServiceInterface getCustomTargetingServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.google.com/apis/ads/publisher/v201408", "CustomTargetingServiceInterfacePort"), CustomTargetingServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMTARGETINGSERVICE_EXCEPTION!= null) {
            throw CUSTOMTARGETINGSERVICE_EXCEPTION;
        }
        return CUSTOMTARGETINGSERVICE_WSDL_LOCATION;
    }

}
