
package com.google.api.ads.adwords.jaxws.v201409.cm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SharedCriterionService", targetNamespace = "https://adwords.google.com/api/adwords/cm/v201409", wsdlLocation = "https://adwords.google.com/api/adwords/cm/v201409/SharedCriterionService?wsdl")
public class SharedCriterionService
    extends Service
{

    private final static URL SHAREDCRITERIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHAREDCRITERIONSERVICE_EXCEPTION;
    private final static QName SHAREDCRITERIONSERVICE_QNAME = new QName("https://adwords.google.com/api/adwords/cm/v201409", "SharedCriterionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://adwords.google.com/api/adwords/cm/v201409/SharedCriterionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHAREDCRITERIONSERVICE_WSDL_LOCATION = url;
        SHAREDCRITERIONSERVICE_EXCEPTION = e;
    }

    public SharedCriterionService() {
        super(__getWsdlLocation(), SHAREDCRITERIONSERVICE_QNAME);
    }

    public SharedCriterionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SharedCriterionServiceInterface
     */
    @WebEndpoint(name = "SharedCriterionServiceInterfacePort")
    public SharedCriterionServiceInterface getSharedCriterionServiceInterfacePort() {
        return super.getPort(new QName("https://adwords.google.com/api/adwords/cm/v201409", "SharedCriterionServiceInterfacePort"), SharedCriterionServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SharedCriterionServiceInterface
     */
    @WebEndpoint(name = "SharedCriterionServiceInterfacePort")
    public SharedCriterionServiceInterface getSharedCriterionServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://adwords.google.com/api/adwords/cm/v201409", "SharedCriterionServiceInterfacePort"), SharedCriterionServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHAREDCRITERIONSERVICE_EXCEPTION!= null) {
            throw SHAREDCRITERIONSERVICE_EXCEPTION;
        }
        return SHAREDCRITERIONSERVICE_WSDL_LOCATION;
    }

}
