
package com.google.api.ads.dfp.jaxws.v201602;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductTemplateService", targetNamespace = "https://www.google.com/apis/ads/publisher/v201602", wsdlLocation = "https://ads.google.com/apis/ads/publisher/v201602/ProductTemplateService?wsdl")
public class ProductTemplateService
    extends Service
{

    private final static URL PRODUCTTEMPLATESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTTEMPLATESERVICE_EXCEPTION;
    private final static QName PRODUCTTEMPLATESERVICE_QNAME = new QName("https://www.google.com/apis/ads/publisher/v201602", "ProductTemplateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ads.google.com/apis/ads/publisher/v201602/ProductTemplateService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTTEMPLATESERVICE_WSDL_LOCATION = url;
        PRODUCTTEMPLATESERVICE_EXCEPTION = e;
    }

    public ProductTemplateService() {
        super(__getWsdlLocation(), PRODUCTTEMPLATESERVICE_QNAME);
    }

    public ProductTemplateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ProductTemplateServiceInterface
     */
    @WebEndpoint(name = "ProductTemplateServiceInterfacePort")
    public ProductTemplateServiceInterface getProductTemplateServiceInterfacePort() {
        return super.getPort(new QName("https://www.google.com/apis/ads/publisher/v201602", "ProductTemplateServiceInterfacePort"), ProductTemplateServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductTemplateServiceInterface
     */
    @WebEndpoint(name = "ProductTemplateServiceInterfacePort")
    public ProductTemplateServiceInterface getProductTemplateServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.google.com/apis/ads/publisher/v201602", "ProductTemplateServiceInterfacePort"), ProductTemplateServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTTEMPLATESERVICE_EXCEPTION!= null) {
            throw PRODUCTTEMPLATESERVICE_EXCEPTION;
        }
        return PRODUCTTEMPLATESERVICE_WSDL_LOCATION;
    }

}
