
package com.google.api.ads.dfp.jaxws.v201405;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * 
 *       Provides methods for managing {@link RateCardCustomization} objects.
 *       <p>
 *       To use this service, you need to have the new sales management solution
 *       enabled on your network. If you do not see a "Sales" tab in
 *       <a href="https://www.google.com/dfp">DoubleClick for Publishers (DFP)</a>,
 *       you will not be able to use this service.
 *     
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RateCardCustomizationServiceInterface", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RateCardCustomizationServiceInterface {


    /**
     * 
     *         Creates a list of new {@link RateCardCustomization} objects.
     *         
     *         @param rateCardCustomizations the rate card customizations to be created
     *         @return the rate card customizations with their IDs filled in
     *       
     * 
     * @param rateCardCustomizations
     * @return
     *     returns java.util.List<com.google.api.ads.dfp.jaxws.v201405.RateCardCustomization>
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "rval", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
    @RequestWrapper(localName = "createRateCardCustomizations", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfacecreateRateCardCustomizations")
    @ResponseWrapper(localName = "createRateCardCustomizationsResponse", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfacecreateRateCardCustomizationsResponse")
    public List<RateCardCustomization> createRateCardCustomizations(
        @WebParam(name = "rateCardCustomizations", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
        List<RateCardCustomization> rateCardCustomizations)
        throws ApiException_Exception
    ;

    /**
     * 
     *         Gets a {@link RateCardCustomizationPage} of {@link RateCardCustomization}
     *         objects that satisfy the given {@link Statement#query}.
     *         
     *         The following fields are supported for filtering:
     *         
     *         <table>
     *         <tr>
     *         <th scope="col">PQL Property</th>
     *         <th scope="col">Object Property</th>
     *         </tr>
     *         <tr>
     *         <td>{@code rateCardId}</td>
     *         <td>{@link RateCardCustomization#rateCardId}</td>
     *         </tr>
     *         <tr>
     *         <td>{@code rateCardCustomizationGroupId}</td>
     *         <td>{@link RateCardCustomization#rateCardCustomizationGroupId}</td>
     *         </tr>
     *         <tr>
     *         <td>{@code id}</td>
     *         <td>{@link RateCardCustomization#id}</td>
     *         </tr>
     *         </table>
     *         
     *         @param filterStatement a Publisher Query Language statement used to filter
     *         a set of rate card customizations.
     *         @return the rate card customizations that match the given filter
     *       
     * 
     * @param filterStatement
     * @return
     *     returns com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationPage
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "rval", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
    @RequestWrapper(localName = "getRateCardCustomizationsByStatement", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfacegetRateCardCustomizationsByStatement")
    @ResponseWrapper(localName = "getRateCardCustomizationsByStatementResponse", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfacegetRateCardCustomizationsByStatementResponse")
    public RateCardCustomizationPage getRateCardCustomizationsByStatement(
        @WebParam(name = "filterStatement", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
        Statement filterStatement)
        throws ApiException_Exception
    ;

    /**
     * 
     *         Performs actions on {@link RateCardCustomization} objects that satisfy the
     *         given {@link Statement#query}.
     *         
     *         @param rateCardCustomizationAction the action to perform
     *         @param filterStatement a Publisher Query Language statement used to filter
     *         a set of rate card customizations.
     *         @return the result of the action performed
     *       
     * 
     * @param rateCardCustomizationAction
     * @param filterStatement
     * @return
     *     returns com.google.api.ads.dfp.jaxws.v201405.UpdateResult
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "rval", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
    @RequestWrapper(localName = "performRateCardCustomizationAction", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfaceperformRateCardCustomizationAction")
    @ResponseWrapper(localName = "performRateCardCustomizationActionResponse", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfaceperformRateCardCustomizationActionResponse")
    public UpdateResult performRateCardCustomizationAction(
        @WebParam(name = "rateCardCustomizationAction", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
        RateCardCustomizationAction rateCardCustomizationAction,
        @WebParam(name = "filterStatement", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
        Statement filterStatement)
        throws ApiException_Exception
    ;

    /**
     * 
     *         Updates the specified {@link RateCardCustomization} objects.
     *         
     *         @param rateCardCustomizations the rate card customizations to be updated
     *         @return the updated rate card customizations
     *       
     * 
     * @param rateCardCustomizations
     * @return
     *     returns java.util.List<com.google.api.ads.dfp.jaxws.v201405.RateCardCustomization>
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "rval", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
    @RequestWrapper(localName = "updateRateCardCustomizations", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfaceupdateRateCardCustomizations")
    @ResponseWrapper(localName = "updateRateCardCustomizationsResponse", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405", className = "com.google.api.ads.dfp.jaxws.v201405.RateCardCustomizationServiceInterfaceupdateRateCardCustomizationsResponse")
    public List<RateCardCustomization> updateRateCardCustomizations(
        @WebParam(name = "rateCardCustomizations", targetNamespace = "https://www.google.com/apis/ads/publisher/v201405")
        List<RateCardCustomization> rateCardCustomizations)
        throws ApiException_Exception
    ;

}
